### ISSUE TITLE
HOME PAGE CHECKLIST

### ISSUE THREAD

**Issue by t4ttc** [carreb/terrahacks#1]
- [x] D-DAY TIMER SPLASH SCREEN
- [x] BLOOD DRIPPING TRANSITION EFFECT
- [x] TIMELINE OF EVENTS
- [x] STICKY TIMER
- [ ] NAVBAR?
- [x] FACTS, GENERAL KNOWLEDGE
- [x] INTERACTIVE ELEMENTS TO CHANGE THE TIME UNTIL D-DAY

**Comment by t4ttc** [comment]
TIMELINE IDEA:
for the timeline, it can start from the beginning of human history, and the timeline shows "YOU ARE HERE" quite close to the end.
